# Generated by Django 5.1.2 on 2024-11-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineschedule',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
