# Generated by Django 5.1.2 on 2024-11-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_lineschedule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='linename',
            name='redcolor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linename',
            name='successcolor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linename',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
