# Generated by Django 5.1.2 on 2024-12-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr', '0002_accessories'),
        ('production', '0007_lineinputfabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLineHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('h1', models.PositiveIntegerField(default=0)),
                ('h2', models.PositiveIntegerField(default=0)),
                ('h3', models.PositiveIntegerField(default=0)),
                ('h4', models.PositiveIntegerField(default=0)),
                ('h5', models.PositiveIntegerField(default=0)),
                ('h6', models.PositiveIntegerField(default=0)),
                ('h7', models.PositiveIntegerField(default=0)),
                ('h8', models.PositiveIntegerField(default=0)),
                ('h9', models.PositiveIntegerField(default=0)),
                ('h10', models.PositiveIntegerField(default=0)),
                ('h11', models.PositiveIntegerField(default=0)),
                ('h12', models.PositiveIntegerField(default=0)),
                ('working_hour', models.PositiveIntegerField(default=0)),
                ('target_qty', models.PositiveIntegerField(default=0)),
                ('total_qty', models.PositiveIntegerField(default=0)),
                ('ho_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.linename')),
                ('style_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.style')),
            ],
        ),
    ]
