# Generated by Django 5.1.2 on 2024-12-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
        ('production', '0008_dailylinehandover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingOperatorGroupModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(blank=True, max_length=255, null=True)),
                ('srno', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee_profile')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.linename')),
            ],
        ),
    ]
