# Generated by Django 5.1.2 on 2024-11-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerName', models.CharField(max_length=225)),
                ('Joined_Date', models.DateField()),
                ('Address', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StyleCode', models.CharField(max_length=225, unique=True)),
                ('ItemName', models.CharField(blank=True, max_length=225, null=True)),
                ('barcode', models.CharField(blank=True, max_length=225, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('BuyerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(blank=True, max_length=225, null=True)),
                ('Qty', models.IntegerField(default=0)),
                ('CMP', models.FloatField(default=0.0)),
                ('ordered_date', models.DateField(blank=True, null=True)),
                ('export_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('BuyerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.buyer')),
                ('StyleCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr.style')),
            ],
        ),
    ]
